using System;
using UnityEngine;
using UnityEngine.SceneManagement;

//note from me, the comments are generated by AI, not me

/// <summary>
/// Centralized audio manager used to play sound effects (SFX) and background music (BG).
/// This class implements a simple singleton so it persists across scene loads and
/// provides global access via SoundManager.Instance.
/// </summary>
public class SoundManager : MonoBehaviour
{
	//// Serialized arrays of SoundBase entries populated in the Inspector. 
	//// 'sounds' are short SFX; 'bgSounds' are background music tracks.
	//[SerializeField] private SoundBase[] sounds, bgSounds;

	//// Flags that control whether SFX and music should be audible. These are loaded
	//// from PlayerPrefs in GetAudioSettings() when a scene is loaded.
	//private bool sfxEnabled, musicEnabled;

	//// Singleton instance reference
	//private static SoundManager instance;
	//public static SoundManager Instance
	//{
	//	get
	//	{
	//		return instance;
	//	}
	//}

	//// Subscribe to sceneLoaded so we can react when a new scene finishes loading.
	//private void OnEnable()
	//{
	//	SceneManager.sceneLoaded += OnSceneLoaded;
	//}

	//// Unsubscribe when disabled to avoid memory leaks / duplicate handlers.
	//private void OnDisable()
	//{
	//	SceneManager.sceneLoaded -= OnSceneLoaded;
	//}

	//// Awake is used to configure the singleton and initialize AudioSource components
	//// for each configured SoundBase entry.
	//private void Awake()
	//{
	//	// Basic singleton pattern: keep the first instance and destroy any duplicates.
	//	if (instance == null)
	//	{
	//		instance = this;
	//		DontDestroyOnLoad(instance); // Persist across scene loads
	//	}
	//	else
	//	{
	//		Destroy(gameObject); // prevent multiple managers
	//	}

	//	// For each SFX entry, add an AudioSource component on this GameObject
	//	// and copy the settings from the SoundBase object to the AudioSource.
	//	foreach (var sound in sounds)
	//	{
	//		sound.source = gameObject.AddComponent<AudioSource>();
	//		sound.source.clip = sound.clip;
	//		sound.source.loop = sound.loop;
	//		sound.source.playOnAwake = sound.playOnAwake;
	//		sound.source.volume = sound.volume;
	//		sound.source.pitch = sound.pitch;
	//		// Note: SoundBase appears to contain a 'spatialBend' field - this is
	//		// assigned to spatialBlend on the AudioSource. If spatialBend is a typo
	//		// in SoundBase it should be corrected there; here we only copy the value.
	//		sound.source.spatialBlend = sound.spatialBend;
	//	}

	//	// Initialize AudioSources for background music entries. BG music typically
	//	// does not use spatialBlend and is usually set to loop.
	//	foreach (var bg in bgSounds)
	//	{
	//		bg.source = gameObject.AddComponent<AudioSource>();
	//		bg.source.clip = bg.clip;
	//		bg.source.loop = bg.loop;
	//		bg.source.volume = bg.volume;
	//		bg.source.pitch = bg.pitch;
	//		bg.source.playOnAwake = bg.playOnAwake;
	//	}
	//}

	///// <summary>
	///// Called when a scene finishes loading. We refresh audio settings from PlayerPrefs
	///// and perform scene-specific audio actions (example: play/stop intro music).
	///// </summary>
	//private void OnSceneLoaded(Scene scene, LoadSceneMode mode)
	//{
	//	GetAudioSettings();

	//	int sceneID = scene.buildIndex;

	//	// Example: play or stop music based on the build index. Adjust to your
	//	// project's scene indexing or use scene.name for a clearer mapping.
	//	switch (sceneID)
	//	{
	//		case 0:
	//			PlayBGMusic("Intro");
	//			break;
	//		case 1:
	//			StopBGMusic("Intro");
	//			break;
	//	}
	//}

	///// <summary>
	///// Play a one-shot sound effect by name. Returns immediately if SFX are disabled.
	///// </summary>
	///// <param name="soundName">The name of the sound entry defined in the Inspector.</param>
	//public void Play(string soundName)
	//{
	//	if (!sfxEnabled) return; // Respect user SFX preference

	//	// Find the SoundBase with the matching name. Array.Find returns null if none.
	//	SoundBase sound = Array.Find(sounds, sound => sound.name == soundName);

	//	if (sound == null) return; // No such sound configured

	//	sound.source.Play();
	//}

	///// <summary>
	///// Start playing background music track by name if music is enabled.
	///// </summary>
	//public void PlayBGMusic(string name)
	//{
	//	if (!musicEnabled) { return; }

	//	SoundBase sound = Array.Find(bgSounds, sound => sound.name == name);

	//	if (sound == null) return;

	//	sound.source.Play();

	//}

	///// <summary>
	///// Stop a background music track by name.
	///// </summary>
	//public void StopBGMusic(string name)
	//{
	//	SoundBase sound = Array.Find(bgSounds, sound => sound.name == name);

	//	if (sound == null) return;

	//	sound.source.Stop();
	//}

	///// <summary>
	///// Load audio-related preferences from PlayerPrefs and set the local flags.
	///// Uses integer values where >0 means enabled.
	///// </summary>
	//private void GetAudioSettings()
	//{
	//	int tempSfx = PlayerPrefs.GetInt("SFX");
	//	// Convert stored integer to bool: any value > 0 means enabled.
	//	sfxEnabled = tempSfx > 0 ? true : tempSfx <= 0 ? false : true;

	//	int tempMusic = PlayerPrefs.GetInt("Music");
	//	musicEnabled = tempMusic > 0 ? true : tempMusic <= 0 ? false : true;
	//}
}
